const SUPABASE_URL = 'https://msnznmoejelmejetsifv.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbnpubW9lamVsbWVqZXRzaWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3OTY4MDQsImV4cCI6MjA4NzM3MjgwNH0.s50XbzGSS2s2cblYYk0oG91AGq5Jgcxc--R2pR98NC0';
window.SUPABASE_CONFIG = { url: SUPABASE_URL, key: SUPABASE_ANON_KEY };
